### ISSUE TITLE
Simple dump/restore on docker using external CRIU results in errors

### ISSUE THREAD

**Issue by koliaskostas** [xemul/criu#192]
Is it possible that the page https://criu.org/Docker could be outdated?

My settings
-----------
Kernel: 4.4.0-21-generic
Debian 16.04
CRIU: 2.0
Docker: 1.11.2

costas@ubuntu1:~$ **docker pull debian**
costas@ubuntu1:~$ **sudo ls /var/lib/docker/aufs/mnt/**
_faa276a6aedfba89f60e7f7afd2dd51c43e09c81b8f0b09491a4f83a24d2e7ed_
costas@ubuntu1:~$ **sudo ls /var/lib/docker/aufs/diff/**
_faa276a6aedfba89f60e7f7afd2dd51c43e09c81b8f0b09491a4f83a24d2e7ed_
costas@ubuntu1:~$ **sudo ls /var/lib/docker/containers/**

costas@ubuntu1:~$ **docker run -d debian /bin/bash -c 'i=0; while true; do echo $i >> counter.log; i=$(expr $i + 1); sleep 3; done'**
_1a80a351851e6121f7f04b0770f25ca0a3215cba9181173b9470eb7e9cda369a_
costas@ubuntu1:~$ **sudo ls -la /var/lib/docker/aufs/mnt/**
_total 20
drwx------ 5 root root 4096 Jul 15 19:00 .
drwx------ 5 root root 4096 Jul 15 13:08 ..
drwxr-xr-x 2 root root 4096 Jul 15 19:00 d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6
drwxr-xr-x 2 root root 4096 Jul 15 19:00 d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6-init
drwxr-xr-x 2 root root 4096 Jul 15 18:57 faa276a6aedfba89f60e7f7afd2dd51c43e09c81b8f0b09491a4f83a24d2e7ed_

costas@ubuntu1:~$ **sudo ls -la /var/lib/docker/aufs/diff/**
_total 20
drwx------  5 root root 4096 Jul 15 19:00 .
drwx------  5 root root 4096 Jul 15 13:08 ..
drwxr-xr-x  4 root root 4096 Jul 15 19:00 d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6
drwxr-xr-x  6 root root 4096 Jul 15 19:00 d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6-init
drwxr-xr-x 21 root root 4096 Jul 15 18:57 faa276a6aedfba89f60e7f7afd2dd51c43e09c81b8f0b09491a4f83a24d2e7ed_

costas@ubuntu1:~$ **sudo ls -la /var/lib/docker/containers/**
_total 12
drwx------ 3 root root 4096 Jul 15 19:00 .
drwx--x--x 9 root root 4096 Jul 15 13:08 ..
drwx------ 3 root root 4096 Jul 15 19:00 1a80a351851e6121f7f04b0770f25ca0a3215cba9181173b9470eb7e9cda369a_

costas@ubuntu1:~$ **docker ps -q | sudo xargs docker inspect --format '{{.State.Pid}}, {{.ID}}'**
_1449, 1a80a351851e6121f7f04b0770f25ca0a3215cba9181173b9470eb7e9cda369a_

costas@ubuntu1:~$ **sudo criu dump -o dump.log -v4 -t 1449 -D check --root /var/lib/docker/aufs/mnt/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6 --ext-mount-map /etc/resolv.conf:/etc/resolv.conf --ext-mount-map /etc/hosts:/etc/hosts --ext-mount-map /etc/hostname:/etc/hostname --ext-mount-map /.dockerinit:/.dockerinit --manage-cgroups --evasive-devices**

results into an error which is described into this log
[dump.log.zip](https://github.com/xemul/criu/files/366997/dump.log.zip)
.

So I am forced to do:

costas@ubuntu1:~$ **sudo criu dump -o dump.log -v4 -t 1449 -D check --root /var/lib/docker/aufs/mnt/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6 --ext-mount-map /etc/resolv.conf:/etc/resolv.conf --ext-mount-map /etc/hosts:/etc/hosts --ext-mount-map /etc/hostname:/etc/hostname --ext-mount-map /.dockerinit:/.dockerinit --ext-mount-map /sys/fs/cgroup/memory:/sys/fs/cgroup/memory --ext-mount-map /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpu,cpuacct --ext-mount-map /sys/fs/cgroup/freezer:/sys/fs/cgroup/freezer --ext-mount-map /sys/fs/cgroup/cpuset:/sys/fs/cgroup/cpuset --ext-mount-map /sys/fs/cgroup/perf_event:/sys/fs/cgroup/perf_event --ext-mount-map /sys/fs/cgroup/devices:/sys/fs/cgroup/devices --ext-mount-map /sys/fs/cgroup/hugetlb:/sys/fs/cgroup/hugetlb --ext-mount-map /sys/fs/cgroup/net_cls,net_prio:/sys/fs/cgroup/net_cls,net_prio --ext-mount-map /sys/fs/cgroup/blkio:/sys/fs/cgroup/blkio --ext-mount-map /sys/fs/cgroup/pids:/sys/fs/cgroup/pids --ext-mount-map /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd --manage-cgroups --evasive-devices**

Then according to the same tutorial I have to reconstruct the filesystem. The syntax of the command contained in the tutorial is wrong so I have to give:

costas@ubuntu1:~$ **sudo mount -t aufs -o br=\
/var/lib/docker/aufs/diff/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6:\
/var/lib/docker/aufs/diff/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6-init:\
/var/lib/docker/aufs/diff/faa276a6aedfba89f60e7f7afd2dd51c43e09c81b8f0b09491a4f83a24d2e7ed \
none /var/lib/docker/aufs/mnt/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6**

which seems to do the job.

To restore I give:
costas@ubuntu1:~$ **sudo criu restore -o restore.log -v4 -d -D check --root /var/lib/docker/aufs/mnt/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6 --ext-mount-map /etc/resolv.conf:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/resolv.conf --ext-mount-map /etc/hosts:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/hosts --ext-mount-map /etc/hostname:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/hostname --ext-mount-map /.dockerinit:/var/lib/docker/init/dockerinit-1.0.0 --ext-mount-map /sys/fs/cgroup/memory:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/memory --ext-mount-map /sys/fs/cgroup/cpu,cpuacct:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/cpu,cpuacct --ext-mount-map /sys/fs/cgroup/freezer:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/freezer --ext-mount-map /sys/fs/cgroup/cpuset:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/cpuset --ext-mount-map /sys/fs/cgroup/perf_event:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/perf_event --ext-mount-map /sys/fs/cgroup/devices:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/devices --ext-mount-map /sys/fs/cgroup/hugetlb:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/hugetlb --ext-mount-map /sys/fs/cgroup/net_cls,net_prio:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/net_cls,net_prio --ext-mount-map /sys/fs/cgroup/blkio:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/blkio --ext-mount-map /sys/fs/cgroup/pids:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/pids --ext-mount-map /sys/fs/cgroup/systemd:/var/lib/docker/containers/d84b62ea92cc73d6691c27b4172b3bc431b25cac134c7de171ccbc4f6cde7ba6/sys/fs/cgroup/systemd --manage-cgroups --evasive-devices**

which results in the error contained in the log
[restore.log.zip](https://github.com/xemul/criu/files/366998/restore.log.zip)
.

Any pointers with the issues or anything I could study to find my way?

**Comment by xemul** [comment]
Well, yes, the Docker C/R is changing rapidly and we don't keep up with updating the page.
@boucher, once you have some free time, would you update (or write a new) article on the wiki to help people play with Docker C/R?

**Comment by koliaskostas** [comment]
@xemul I am also willing to write articles about several CRIU use cases (I registered at the wiki) but so far I have stumbled against this CR Docker scenario and I can't find enough resources to problem solve.

**Comment by koliaskostas** [comment]
@xemul what it possible to get an opinion on the error, especially the second one?

**Comment by boucher** [comment]
@xemul I'll take a stab at updating the wiki. 

@koliaskostas I haven't really played around with checkpoint/restore from outside of Docker. I'm not sure if that's an actual goal of yours, or just what seemed like the easiest thing to do. If it's the latter, I recommend trying this:

https://github.com/boucher/docker/releases/tag/v1.10_2-16-16-experimental

It contains a pre-built Docker binary that supports checkpoint/restore. It's running on Docker 1.10. If, for some reason, you need a newer version of Docker, you can try building the branch pointed to in this PR: 

https://github.com/docker/docker/pull/22049

It should be working, though it's slightly more difficult to run just because Docker now has been split into multiple processes (and it isn't yet available as a pre-built binary).

**Comment by boucher** [comment]
Posted some updated info to the wiki.

**Comment by koliaskostas** [comment]
@boucher I am afraid that I have to play with external CRIU to a Docker process because to the best of my knowledge the inline checkpoint/restore options of the experimental Docker do not support incremental checkpoints. That is my ultimate goal. Can you verify that inline c/r in Docker still doesn't support this functionality?

**Comment by koliaskostas** [comment]
@boucher And the fact that you took time to update the wiki **is much appreciated**. I will dedicate some more time in figuring out the problems with the _external checkpoint restore_ paragraph (which I believe also contain some syntax errors) before I call it a day. In the mean time I would highly appreciate if someone would mention the environment settings so I can possibly reproduce the example myself.

**Comment by boucher** [comment]
@koliaskostas Although incremental checkpointing isn't supported, you may find that it's not *that* challenging to add. The hardest problem is just coordinating the changes up through the various components. I'd certainly like to see that change myself and would be happy to point you to the right places.

**Comment by koliaskostas** [comment]
@boucher Oh yes! Please share whatever you think would help. I am trying to reproduce experiments I find on the Internet under the assumption that this is doable out of the box with external CRIU use on a Docker container running Apache. My ultimate goal is to achieve live migration of an Apache server and there are various documents on the wiki page that verify that the general idea is doable. So far, I am coming across some weird errors even though I do things "by the book".

**Comment by boucher** [comment]
You should look at p.haul + docker if your goal is live migration. Or, if you don't actually care that much about Docker specifically, you could look into @marcosnils project https://github.com/marcosnils/cmt/

**Comment by boucher** [comment]
Again, just without knowing your specific issue, I might suggest getting things working without incremental checkpointing first, since I believe adding that will probably not be your hardest problem.

**Comment by xemul** [comment]
@koliaskostas , about the errors in logs -- yes, sure. Have you tried the @boucher 's suggestion? If something fails there, I'll be glad to help.

And about live migration -- yes, the p.haul stuff we go (github/xemul/p.haul) is for live migration, but the Docker support is not in the perfect shape there yet.

**Comment by koliaskostas** [comment]
@xemul Thanks for willing to help. Yes, I experimented with @boucher suggestion. I decided to keep everything basic. My goal has turned into achieve live migration by using the inline checkpoint/restore functionality of the experimental docker version. As a first step I tried to checkpoint/restore an docker-apache within the same container. I will share my experiences (along with error log files) here, or I will open another thread whichever you prefer.

**Comment by xemul** [comment]
I think one problem per issue would be better :)

**Comment by hodiapa** [comment]
@koliaskostas : did you get to the point of implementing an incremental checkpoint? I am also very interested in this effort.

**Comment by koliaskostas** [comment]
I conducted a series of different experiments.
For example I switched from ab to parallel curl and there are definitely
errors when trying to dump especially when there is a great number of
requests.
I am on vacations right now so i cant provide much help with dump logs etc.
but it’s he first thing on my list as soon as I come back.

I there might be still some work to be done with transient tcp reqs but i
ll get back to that soon.




On October 24, 2016 at 11:20:40 PM, hodiapa (notifications@github.com)
wrote:

@koliaskostas <https://github.com/koliaskostas> : did you get to the point
of implementing an incremental checkpoint? I am also very interested in
this effort.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xemul/criu/issues/192#issuecomment-255854185>, or mute
the thread
